const COLORS = {
    PRIMARY: "#56A99d",
     PRIMARY_DARK: "#329182",
    PRIMARY_DARK_EXTRA: "#0E705d",
    PRIMARY_LIGHT: "#9FCEC0",
    PRIMARY_LIGHT_EXTRA: "#BBDDDC",
    PRIMARY_PINK: "#FE409A"
}
